### ISSUE TITLE
Recaptcha: incorrect docstring in composition settings

### ISSUE THREAD

**Issue by sam-b0t** [sveetch/cookiecutter-bireli#51]
https://github.com/sveetch/cookiecutter-bireli/blob/b077e896c0954a52224a842109d2465796f949cc/%7B%7B%20cookiecutter.project_name%20%7D%7D/composition_repository/recaptcha/settings.py#L13-L15

**Comment by sveetch** [comment]
Done in v0.3.13-pre.2
